languages = {
    "af": "Afrikaans",
    "ar": "Arabic",
    "bg": "Bulgarian",
    "yue yue": "Cantonese (Spoken)",
    "yue-Hant": "Cantonese (Script)",
    "ca": "Catalan",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "nl": "Dutch",
    "nl-BE": "Dutch (Belgium)",
    "nl-NL": "Dutch (Netherlands)",
    "en": "English",
    "en-AU": "English (Australia)",
    "en-CA": "English (Canada)",
    "en-FR": "English (France)",
    "en-DE": "English (Germany)",
    "en-IE": "English (Ireland)",
    "en-NZ": "English (New Zealand)",
    "en-GB": "English (United Kingdom)",
    "en-US": "English (United States)",
    "et": "Estonian",
    "fi": "Finnish",
    "fr": "French",
    "fr-BE": "French (Belgium)",
    "fr-CA": "French (Canada)",
    "fr-FR": "French (France)",
    "fr-CH": "French (Switzerland)",
    "de": "German",
    "de-AT": "German (Austria)",
    "de-DE": "German (Germany)",
    "de-CH": "German (Switzerland)",
    "el": "Greek",
    "el-CY": "Greek (Cyprus)",
    "he": "Hebrew",
    "hi": "Hindi",
    "hu": "Hungarian",
    "is": "Icelandic",
    "id": "Indonesian",
    "it": "Italian",
    "it-IT": "Italian (Italy)",
    "ja": "Japanese",
    "kk": "Kazakh",
    "ko": "Korean",
    "lo": "Lao",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "lb": "Luxembourgish",
    "ms": "Malay",
    "mt": "Maltese",
    "cmn-Hans": "Mandarin (Simplified Script)",
    "cmn": "Mandarin (Spoken)",
    "cmn-Hant": "Mandarin (Traditional Script)",
    "no": "Norwegian",
    "pl": "Polish",
    "pt": "Portuguese",
    "pt-BR": "Portuguese (Brazil)",
    "pt-PT": "Portuguese (Portugal)",
    "ro": "Romanian",
    "ru": "Russian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "es": "Spanish",
    "es-419": "Spanish (Latin America)",
    "es-MX": "Spanish (Mexico)",
    "es-ES": "Spanish (Spain)",
    "sv": "Swedish",
    "tl": "Tagalog",
    "ta": "Tamil",
    "te": "Telugu",
    "th": "Thai",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "vi": "Vietnamese",
    "zu": "Zulu"
}
