genres = {
    "": "",
    "Action & Adventure": "ACTION-ADVENTURE-00",
    "African": "AFRICAN-00",
    "Anime": "ANIME-00",
    "Bollywood": "BOLLYWOOD-00",
    "Classics": "CLASSICS-00",
    "Comedy": "COMEDY-00",
    "Concert Films": "CONCERT-FILMS-00",
    "Documentary": "DOCUMENTARY-00",
    "Drama": "DRAMA-00",
    "Foreign": "FOREIGN-00",
    "Holiday": "HOLIDAY-00",
    "Horror": "HORROR-00",
    "Independent": "INDEPENDENT-00",
    "Kids & Family": "KIDS-FAMILY-00",
    "Made for TV": "MADE-FOR-TV-00",
    "Middle Eastern": "MIDDLE-EASTERN-00",
    "Music Documentaries": "MUSIC-DOCUMENTARIES-00",
    "Music Feature Film": "MUSIC-FEATURE-FILMS-00",
    "Musicals": "MUSICALS-00",
    "Regional Indian": "REGIONAL-INDIAN-00",
    "Romance": "ROMANCE-00",
    "Russian": "RUSSIAN-00",
    "Sci-Fi & Fantasy": "SCIFI-FANTASY-00",
    "Short Films": "SHORT-FILMS-00",
    "Special Interest": "SPECIAL-INTEREST-00",
    "Sports": "SPORTS-00",
    "Thriller": "THRILLER-00",
    "Turkish": "TURKISH-00",
    "Urban": "URBAN-00",
    "Western": "WESTERN-00"
}